/*
  ==============================================================================
    PluginProcessor.cpp - JUCE plugin processor with Vult DSP
    Generated by DSPLab
  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
DSPLabVultAudioProcessor::DSPLabVultAudioProcessor()
#ifndef JucePlugin_PreferredChannelConfigurations
    : AudioProcessor(BusesProperties()
#if ! JucePlugin_IsMidiEffect
#if ! JucePlugin_IsSynth
        .withInput("Input", juce::AudioChannelSet::stereo(), true)
#endif
        .withOutput("Output", juce::AudioChannelSet::stereo(), true)
#endif
    )
#endif
{
}

DSPLabVultAudioProcessor::~DSPLabVultAudioProcessor()
{
}

//==============================================================================
const juce::String DSPLabVultAudioProcessor::getName() const
{
    return JucePlugin_Name;
}

bool DSPLabVultAudioProcessor::acceptsMidi() const
{
#if JucePlugin_WantsMidiInput
    return true;
#else
    return false;
#endif
}

bool DSPLabVultAudioProcessor::producesMidi() const
{
#if JucePlugin_ProducesMidiOutput
    return true;
#else
    return false;
#endif
}

bool DSPLabVultAudioProcessor::isMidiEffect() const
{
#if JucePlugin_IsMidiEffect
    return true;
#else
    return false;
#endif
}

double DSPLabVultAudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int DSPLabVultAudioProcessor::getNumPrograms()
{
    return 1;
}

int DSPLabVultAudioProcessor::getCurrentProgram()
{
    return 0;
}

void DSPLabVultAudioProcessor::setCurrentProgram(int index)
{
}

const juce::String DSPLabVultAudioProcessor::getProgramName(int index)
{
    return {};
}

void DSPLabVultAudioProcessor::changeProgramName(int index, const juce::String& newName)
{
}

//==============================================================================
void DSPLabVultAudioProcessor::prepareToPlay(double sampleRate, int samplesPerBlock)
{
    m_vult.prepareToPlay(sampleRate, samplesPerBlock);
}

void DSPLabVultAudioProcessor::releaseResources()
{
    m_vult.releaseResources();
}

#ifndef JucePlugin_PreferredChannelConfigurations
bool DSPLabVultAudioProcessor::isBusesLayoutSupported(const BusesLayout& layouts) const
{
#if JucePlugin_IsMidiEffect
    juce::ignoreUnused(layouts);
    return true;
#else
    if (layouts.getMainOutputChannelSet() != juce::AudioChannelSet::mono()
        && layouts.getMainOutputChannelSet() != juce::AudioChannelSet::stereo())
        return false;

#if ! JucePlugin_IsSynth
    if (layouts.getMainOutputChannelSet() != layouts.getMainInputChannelSet())
        return false;
#endif

    return true;
#endif
}
#endif

void DSPLabVultAudioProcessor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages)
{
    m_vult.processBlock(buffer, midiMessages);
}

//==============================================================================
bool DSPLabVultAudioProcessor::hasEditor() const
{
    return true;
}

juce::AudioProcessorEditor* DSPLabVultAudioProcessor::createEditor()
{
    return new DSPLabVultAudioProcessorEditor(*this);
}

//==============================================================================
void DSPLabVultAudioProcessor::getStateInformation(juce::MemoryBlock& destData)
{
}

void DSPLabVultAudioProcessor::setStateInformation(const void* data, int sizeInBytes)
{
}

//==============================================================================
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new DSPLabVultAudioProcessor();
}
