/*
  ==============================================================================
    PluginEditor.h - JUCE plugin editor
    Generated by DSPLab
  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

class DSPLabVultAudioProcessorEditor : public juce::AudioProcessorEditor
{
public:
    DSPLabVultAudioProcessorEditor(DSPLabVultAudioProcessor&);
    ~DSPLabVultAudioProcessorEditor() override;

    void paint(juce::Graphics&) override;
    void resized() override;

private:
    DSPLabVultAudioProcessor& audioProcessor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(DSPLabVultAudioProcessorEditor)
};
