/*
  ==============================================================================
    PluginEditor.cpp - JUCE plugin editor
    Generated by DSPLab
  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
DSPLabVultAudioProcessorEditor::DSPLabVultAudioProcessorEditor(DSPLabVultAudioProcessor& p)
    : AudioProcessorEditor(&p), audioProcessor(p)
{
    setSize(400, 300);
}

DSPLabVultAudioProcessorEditor::~DSPLabVultAudioProcessorEditor()
{
}

//==============================================================================
void DSPLabVultAudioProcessorEditor::paint(juce::Graphics& g)
{
    g.fillAll(getLookAndFeel().findColour(juce::ResizableWindow::backgroundColourId));

    g.setColour(juce::Colours::white);
    g.setFont(juce::FontOptions(15.0f));
    g.drawFittedText("DSPLab Vult Plugin", getLocalBounds(), juce::Justification::centred, 1);
}

void DSPLabVultAudioProcessorEditor::resized()
{
}
