/*
  ==============================================================================
    VultProcessor.cpp - JUCE wrapper for Vult DSP code
    Generated by DSPLab

    Copy this file to your JUCE project's Source folder and include
    the generated Vult DSP files (dsplab.h, dsplab.cpp, dsplab.tables.h)
  ==============================================================================
*/

#include "VultProcessor.h"
#include <cstring>

// Include your generated Vult code here:
// #include "dsplab.h"

VultProcessor::VultProcessor()
    : m_sampleRate(44100.0)
{
    memset(m_ccValues, 0, sizeof(m_ccValues));
    // Initialize Vult DSP
    // dsplab_process_init(m_data);
    // dsplab_default(m_data);
}

VultProcessor::~VultProcessor()
{
}

void VultProcessor::prepareToPlay(double sampleRate, int samplesPerBlock)
{
    m_sampleRate = sampleRate;
    // dsplab_process_init(m_data);
    // dsplab_default(m_data);
}

void VultProcessor::releaseResources()
{
}

void VultProcessor::processBlock(juce::AudioBuffer<float>& buffer, juce::MidiBuffer& midiMessages)
{
    const int numSamples = buffer.getNumSamples();
    const int numChannels = buffer.getNumChannels();

    // Process MIDI
    for (const auto metadata : midiMessages)
    {
        const auto message = metadata.getMessage();
        
        if (message.isNoteOn())
        {
            // dsplab_noteOn(m_data, message.getNoteNumber(), message.getVelocity(), message.getChannel());
        }
        else if (message.isNoteOff())
        {
            // dsplab_noteOff(m_data, message.getNoteNumber(), message.getChannel());
        }
        else if (message.isController())
        {
            // dsplab_controlChange(m_data, message.getControllerNumber(), message.getControllerValue(), message.getChannel());
        }
    }

    // Process audio - modify based on your Vult code's I/O configuration
    float* leftChannel = buffer.getWritePointer(0);
    float* rightChannel = numChannels > 1 ? buffer.getWritePointer(1) : leftChannel;

    for (int i = 0; i < numSamples; i++)
    {
        float input = leftChannel[i];
        
        // Replace with your Vult process call, e.g.:
        // float outputL, outputR;
        // dsplab_process(m_data, input, outputL, outputR);
        
        float outputL = input;
        float outputR = input;
        
        leftChannel[i] = outputL;
        if (numChannels > 1) {
            rightChannel[i] = outputR;
        }
    }
}

void VultProcessor::setParameter(int cc, float value)
{
    if (cc >= 0 && cc < 128) {
        m_ccValues[cc] = value;
        // dsplab_controlChange(m_data, cc, (int)(value * 127), 1);
    }
}

float VultProcessor::getParameter(int cc) const
{
    if (cc >= 0 && cc < 128) {
        return m_ccValues[cc];
    }
    return 0.0f;
}

void VultProcessor::noteOn(int note, int velocity, int channel)
{
    // dsplab_noteOn(m_data, note, velocity, channel);
}

void VultProcessor::noteOff(int note, int channel)
{
    // dsplab_noteOff(m_data, note, channel);
}

void VultProcessor::reset()
{
    // dsplab_process_init(m_data);
    // dsplab_default(m_data);
    memset(m_ccValues, 0, sizeof(m_ccValues));
}
